# Generated by Django 3.2.24 on 2024-03-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_videos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(upload_to='images/%y/%m/%d'),
        ),
    ]
