# Generated by Django 3.2.24 on 2024-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_videos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
