# Generated by Django 3.2.24 on 2024-03-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_videos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
        migrations.AlterModelTable(
            name='videos',
            table=None,
        ),
    ]
