# Generated by Django 3.2.24 on 2024-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/%y')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.FileField(upload_to='videos/%Y'),
        ),
    ]
