# Generated by Django 3.2.24 on 2024-03-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20240310_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='content',
        ),
        migrations.AddField(
            model_name='courses',
            name='pdf',
            field=models.FileField(default='default.pdf', upload_to='course_pdfs/'),
        ),
    ]
