# Generated by Django 3.2.24 on 2024-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='link',
        ),
        migrations.AddField(
            model_name='projects',
            name='pdff',
            field=models.FileField(default='default.pdf', upload_to='project_pdfs/'),
        ),
    ]
